# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(494, 546)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 491, 501))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 201, 221))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 40, 171, 31))
        self.label.setObjectName("label")
        self.div_num_a = QtWidgets.QSpinBox(self.groupBox)
        self.div_num_a.setGeometry(QtCore.QRect(20, 80, 151, 31))
        self.div_num_a.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.div_num_a.setMinimum(1)
        self.div_num_a.setMaximum(9)
        self.div_num_a.setProperty("value", 3)
        self.div_num_a.setObjectName("div_num_a")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 130, 171, 31))
        self.label_2.setObjectName("label_2")
        self.div_num_b = QtWidgets.QSpinBox(self.groupBox)
        self.div_num_b.setGeometry(QtCore.QRect(20, 170, 151, 31))
        self.div_num_b.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.div_num_b.setMinimum(1)
        self.div_num_b.setMaximum(9)
        self.div_num_b.setProperty("value", 2)
        self.div_num_b.setObjectName("div_num_b")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(240, 10, 231, 281))
        self.groupBox_2.setObjectName("groupBox_2")
        self.div_res_no = QtWidgets.QRadioButton(self.groupBox_2)
        self.div_res_no.setGeometry(QtCore.QRect(10, 30, 181, 41))
        self.div_res_no.setChecked(True)
        self.div_res_no.setObjectName("div_res_no")
        self.div_res_yes = QtWidgets.QRadioButton(self.groupBox_2)
        self.div_res_yes.setGeometry(QtCore.QRect(10, 70, 181, 31))
        self.div_res_yes.setChecked(False)
        self.div_res_yes.setObjectName("div_res_yes")
        self.div_res_mix = QtWidgets.QRadioButton(self.groupBox_2)
        self.div_res_mix.setGeometry(QtCore.QRect(10, 100, 181, 41))
        self.div_res_mix.setObjectName("div_res_mix")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 150, 191, 121))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox_3)
        self.horizontalSlider.setGeometry(QtCore.QRect(10, 40, 171, 21))
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(9)
        self.horizontalSlider.setProperty("value", 4)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.div_num_v = QtWidgets.QSpinBox(self.groupBox_3)
        self.div_num_v.setGeometry(QtCore.QRect(20, 70, 151, 31))
        self.div_num_v.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.div_num_v.setMinimum(1)
        self.div_num_v.setMaximum(9)
        self.div_num_v.setProperty("value", 4)
        self.div_num_v.setObjectName("div_num_v")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(110, 350, 81, 31))
        self.label_3.setObjectName("label_3")
        self.div_num_l = QtWidgets.QSpinBox(self.tab)
        self.div_num_l.setGeometry(QtCore.QRect(200, 350, 151, 31))
        self.div_num_l.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.div_num_l.setMinimum(1)
        self.div_num_l.setMaximum(999)
        self.div_num_l.setProperty("value", 9)
        self.div_num_l.setObjectName("div_num_l")
        self.div_generate = QtWidgets.QPushButton(self.tab)
        self.div_generate.setGeometry(QtCore.QRect(130, 400, 211, 41))
        self.div_generate.setObjectName("div_generate")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(110, 350, 81, 31))
        self.label_4.setObjectName("label_4")
        self.mul_generate = QtWidgets.QPushButton(self.tab_2)
        self.mul_generate.setGeometry(QtCore.QRect(130, 400, 211, 41))
        self.mul_generate.setObjectName("mul_generate")
        self.mul_num_l = QtWidgets.QSpinBox(self.tab_2)
        self.mul_num_l.setGeometry(QtCore.QRect(200, 350, 151, 31))
        self.mul_num_l.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mul_num_l.setMinimum(1)
        self.mul_num_l.setMaximum(999)
        self.mul_num_l.setProperty("value", 9)
        self.mul_num_l.setObjectName("mul_num_l")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(240, 10, 231, 321))
        self.groupBox_4.setObjectName("groupBox_4")
        self.mul_no = QtWidgets.QRadioButton(self.groupBox_4)
        self.mul_no.setGeometry(QtCore.QRect(10, 30, 181, 41))
        self.mul_no.setChecked(True)
        self.mul_no.setObjectName("mul_no")
        self.mul_yes = QtWidgets.QRadioButton(self.groupBox_4)
        self.mul_yes.setGeometry(QtCore.QRect(10, 70, 181, 31))
        self.mul_yes.setChecked(False)
        self.mul_yes.setObjectName("mul_yes")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 110, 191, 201))
        self.groupBox_5.setObjectName("groupBox_5")
        self.mul_num_c = QtWidgets.QSpinBox(self.groupBox_5)
        self.mul_num_c.setGeometry(QtCore.QRect(20, 80, 151, 31))
        self.mul_num_c.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mul_num_c.setMinimum(1)
        self.mul_num_c.setMaximum(9)
        self.mul_num_c.setProperty("value", 2)
        self.mul_num_c.setObjectName("mul_num_c")
        self.mul_num_d = QtWidgets.QSpinBox(self.groupBox_5)
        self.mul_num_d.setGeometry(QtCore.QRect(20, 160, 151, 31))
        self.mul_num_d.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mul_num_d.setMinimum(1)
        self.mul_num_d.setMaximum(9)
        self.mul_num_d.setProperty("value", 2)
        self.mul_num_d.setObjectName("mul_num_d")
        self.label_7 = QtWidgets.QLabel(self.groupBox_5)
        self.label_7.setGeometry(QtCore.QRect(20, 40, 171, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_5)
        self.label_8.setGeometry(QtCore.QRect(20, 120, 171, 31))
        self.label_8.setObjectName("label_8")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 10, 201, 221))
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_5 = QtWidgets.QLabel(self.groupBox_6)
        self.label_5.setGeometry(QtCore.QRect(20, 40, 171, 31))
        self.label_5.setObjectName("label_5")
        self.mul_num_a = QtWidgets.QSpinBox(self.groupBox_6)
        self.mul_num_a.setGeometry(QtCore.QRect(20, 80, 151, 31))
        self.mul_num_a.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mul_num_a.setMinimum(1)
        self.mul_num_a.setMaximum(9)
        self.mul_num_a.setProperty("value", 3)
        self.mul_num_a.setObjectName("mul_num_a")
        self.label_6 = QtWidgets.QLabel(self.groupBox_6)
        self.label_6.setGeometry(QtCore.QRect(20, 130, 171, 31))
        self.label_6.setObjectName("label_6")
        self.mul_num_b = QtWidgets.QSpinBox(self.groupBox_6)
        self.mul_num_b.setGeometry(QtCore.QRect(20, 170, 151, 31))
        self.mul_num_b.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mul_num_b.setMinimum(1)
        self.mul_num_b.setMaximum(9)
        self.mul_num_b.setProperty("value", 2)
        self.mul_num_b.setObjectName("mul_num_b")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "桁数"))
        self.label.setText(_translate("MainWindow", "割られる数の桁"))
        self.label_2.setText(_translate("MainWindow", "割る数の桁"))
        self.groupBox_2.setTitle(_translate("MainWindow", "あまり"))
        self.div_res_no.setText(_translate("MainWindow", "なし"))
        self.div_res_yes.setText(_translate("MainWindow", "あり"))
        self.div_res_mix.setText(_translate("MainWindow", "ミックス"))
        self.groupBox_3.setTitle(_translate("MainWindow", "あまり「あり」の数"))
        self.label_3.setText(_translate("MainWindow", "問題数"))
        self.div_generate.setText(_translate("MainWindow", "問題作成"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "割り算"))
        self.label_4.setText(_translate("MainWindow", "問題数"))
        self.mul_generate.setText(_translate("MainWindow", "問題作成"))
        self.groupBox_4.setTitle(_translate("MainWindow", "小数点"))
        self.mul_no.setText(_translate("MainWindow", "なし"))
        self.mul_yes.setText(_translate("MainWindow", "あり"))
        self.groupBox_5.setTitle(_translate("MainWindow", "小数点以下桁数"))
        self.label_7.setText(_translate("MainWindow", "ひとつめの数"))
        self.label_8.setText(_translate("MainWindow", "ふたつめの数"))
        self.groupBox_6.setTitle(_translate("MainWindow", "桁数"))
        self.label_5.setText(_translate("MainWindow", "割られる数の桁"))
        self.label_6.setText(_translate("MainWindow", "割る数の桁"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "掛け算"))

